spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lab?serverTimezone=UTC
    username: root
    password: 362573
    driver-class-name: com.mysql.cj.jdbc.Driver

# Mybatis配置
mybatis:
  # 配置XML映射文件中指定的实体类别名路径
  type-aliases-package: hnist.javafx.kqms.pojo
  # 配置MyBatis的xml配置文件路径
  mapper-locations: classpath:mapper/*.xml